name: Build

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Get REPO Name
      run: |
        echo "REPO=$(echo $GITHUB_REPOSITORY | sed 's/WE1ZARD\///')" >> $GITHUB_ENV
    
    - name: 'Pack'
      run: |
        cd ./jpg
        zip -rq '${{env.REPO}}_jpg.zip' ./atmosphere
        cd ../nojpg
        zip -rq '${{env.REPO}}_nojpg.zip' ./atmosphere
        cd ../
        mv ./jpg/${{env.REPO}}_jpg.zip ./
        mv ./nojpg/${{env.REPO}}_nojpg.zip ./
    - name: Release
      uses: softprops/action-gh-release@master
      with:
        draft: false
        generate_release_notes: false
        tag_name: 'latest'
        files: |
          ${{env.REPO}}_jpg.zip
          ${{env.REPO}}_nojpg.zip